### ISSUE TITLE
TypeError: _.has is not a function

### ISSUE THREAD

**Issue by borekb** [XVincentX/vscode-apielements#67]
After opening an .apib file, I get this error:

```
The Api Elements server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

This is in the output panel:

```
C:\Users\borek\.vscode\extensions\vncz.vscode-apielements-0.6.0\server\node_modules\uptown\lib\uptown.js:10
  if (protoProps && _.has(protoProps, 'constructor')) {
                      ^

TypeError: _.has is not a function
    at Function.exports.extend (C:\Users\borek\.vscode\extensions\vncz.vscode-apielements-0.6.0\server\node_modules\uptown\lib\uptown.js:10:23)
    at exports.createClass (C:\Users\borek\.vscode\extensions\vncz.vscode-apielements-0.6.0\server\node_modules\uptown\lib\uptown.js:42:15)
    at Object.<anonymous> (C:\Users\borek\.vscode\extensions\vncz.vscode-apielements-0.6.0\server\node_modules\minim\lib\namespace.js:16:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
[Info  - 15:11:17] Connection to server got closed. Server will restart.
```

**Comment by XVincentX** [comment]
@borekb 
Hey!
Thanks a lot for opening the issue.
According to the error you posted, it seems like it's related to the underlying parser.
Would it be possible to share the offending document here, so I can have a look into?

Have a nice day sir!

**Comment by borekb** [comment]
Strange, I cannot reproduce it on another machine I have VS Code installed on. There was a different error in the top message bar:

```
Cannot read property 'content' of undefined
```

but after I dismissed it, I cannot reproduce it either.

The Blueprint document contains one semantic error (repeated endpoint) if that's of any help. Something like:

```apib
FORMAT: 1A

# Test

Sample API

# Group Sites

## All sites [GET /sites]

+ Response 200 (application/json)

        [
            (Site)
        ]

## Create site [POST /sites]

Create new site

+ Request  (application/json)

        {
            "name": "Some site"
        }

+ Response 201 (application/json)

        (Site)

# Data Structures

## Site (object):
+ name: Some site (string)

```

**Comment by XVincentX** [comment]
Thanks a lot for the data. I will try to have a look one of these days and issue a fix if it's an error on my side.

Have a great weekend!

**Comment by XVincentX** [comment]
I am not able to reproduce it either.

![image](https://cloud.githubusercontent.com/assets/1416224/22627012/0d2ce340-ebba-11e6-90c6-d71cc68b92bd.png)


I'll try to update the parser and the libraries and publish a maintenance release for that anyway.

**Comment by XVincentX** [comment]
Done - let me know if you encounter the issue again or not. It should now be using latest parser version.

**Comment by borekb** [comment]
Tried 0.6.1 and it procudes this:

```
C:\Users\Borek\.vscode\extensions\vncz.vscode-apielements-0.6.1\server\node_modules\drafter.js\lib\drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname, process, global) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module;if(!Module){Module={}}Module["ready"]=false;Module["log"]=(function(text){console.log("drafter.js: "+text)});Module["logErr"]=(function(text){console.error("drafter.js: "+text)});Module["onRuntimeInitialized"]=(function(){this.ready=true});var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONME

Error: Cannot find module 'fury-adapter-swagger'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Borek\.vscode\extensions\vncz.vscode-apielements-0.6.1\server\parser.js:4:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 16:11:03] Connection to server got closed. Server will restart.
```

**Comment by XVincentX** [comment]
Gosh!

**Comment by XVincentX** [comment]
@borekb What about now?

**Comment by borekb** [comment]
0.6.2:

![image](https://cloud.githubusercontent.com/assets/101152/22627255/cb481822-ebbf-11e6-9b78-0ccefb866140.png)


```
C:\Users\Borek\.vscode\extensions\vncz.vscode-apielements-0.6.2\server\node_modules\drafter.js\lib\drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname, process, global) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module;if(!Module){Module={}}Module["ready"]=false;Module["log"]=(function(text){console.log("drafter.js: "+text)});Module["logErr"]=(function(text){console.error("drafter.js: "+text)});Module["onRuntimeInitialized"]=(function(){this.ready=true});var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONME

Error: Cannot find module 'fury-adapter-swagger'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Borek\.vscode\extensions\vncz.vscode-apielements-0.6.2\server\parser.js:4:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 16:24:46] Connection to server got closed. Server will restart.
```

**Comment by XVincentX** [comment]
Cool, it seems like there’s something terribly wrong with the new module.

**Comment by borekb** [comment]
Appreciate your effort very much. 👏

**Comment by XVincentX** [comment]
Yet another try, please!

**Comment by borekb** [comment]
0.6.3: still the same. I actually tried uninstalling, restarting Code and installing again. Yields the same error.

**Comment by XVincentX** [comment]
I’m terribly sorry, there’s something wrong with the packages but I’m not able to figure out it yet. Keep going!
V.

**Comment by borekb** [comment]
You don't see the same error as I do? I'm trying the exact snippet from https://github.com/XVincentX/vscode-apielements/issues/67#issuecomment-277377992.

**Comment by XVincentX** [comment]
I’m not on a computer where I can try the things.
Would you mind give it another try?
V.

**Comment by borekb** [comment]
All is alright now! Thanks.

I also noticed that in the Output panel, there is no longer "API elements" option in the dropdown box. Is it related, or is it just a lack of error output that the list element is not there?

**Comment by XVincentX** [comment]
It's not relate to the extension - I think it's simply because you've removed it and it lost its settings.
Not sure how to restore it.

Anyway, I'm not outputting any info so, if I recall correctly, you should not lose any info.
